// ============================================================================
//  TD08 — Fluctuation–Dissipation and Brownian Motion
//
//  1D Rayleigh gas: heavy vortex (M = 100 m) immersed in a TD02-MB bath.
//  Collisions generated by exact flux-weighted thinning; the SAME collision
//  stream produces the kicks (at rest) and the drag (in motion). There is NO
//  noise-amplitude parameter anywhere in this file — if the Einstein relation
//  holds, it is because one statistic governs both faces.
//
//  P0  equilibrium: <M V^2> = k_B T (no thermostat acts on V).
//  P1  Brownian walk: MSD(lag) = 2D(lag - tau) fit over disjoint increments.
//  P2  Einstein relation: D/(mu k_B T) = 1 +- 2% at T = 1 and T = 4.
//  P3  FDT at zero frequency: clamped force noise S_F(0) vs 2 gamma k_B T.
//  P4  Stokes-Einstein/FD02 closure: DEFERRED (declared in RUN_LOG).
//
//  Author: J. C. Harvey, Melbourne. 2026-07-03.
//  Build: cl /std:c++20 /EHsc /O2 /utf-8 /I Engine/include td08_fdt_brownian.cpp
// ============================================================================

#include <sdt/laws.hpp>
#include <cstdio>
#include <cmath>
#include <vector>
#include <random>

namespace {
const double kB_SI = sdt::laws::measured::k_B;   // unit bridge only
std::mt19937_64 rng(20260703ULL);

constexpr double Mh = 100.0;   // heavy mass (bath m = 1)
constexpr double nb = 1.0;     // bath number density (1D)

struct Walker { double x = 0, V = 0, t = 0; };

struct RunStats {
    double sumV2dt = 0;
    long   ncoll = 0;
    double imp2 = 0;           // sum of squared impulses (clamped mode)
};

// Advance walker to tmax under force F, colliding with a bath at temperature T.
// Exact thinning: candidates at Poisson rate Lam = nb*C, accepted w.p. |v-V|/C.
// If xrec != nullptr, record x every xrec_dt (for MSD increments).
RunStats evolve(Walker& w, double tmax, double T, double F, bool clampV,
                std::vector<double>* xrec = nullptr, double xrec_dt = 0) {
    const double sig = std::sqrt(T);
    const double C = 8.0 * sig + 0.5;
    const double Lam = nb * C;
    std::exponential_distribution<double> edt(Lam);
    std::normal_distribution<double> gv(0.0, sig);
    std::uniform_real_distribution<double> u01(0.0, 1.0);
    RunStats S;
    double next_rec = xrec_dt;
    while (w.t < tmax) {
        double dt = edt(rng);
        if (w.t + dt > tmax) dt = tmax - w.t;
        const double a = clampV ? 0.0 : F / Mh;
        // record x at sample instants inside this free flight
        while (xrec && next_rec <= w.t + dt && next_rec <= tmax) {
            const double h = next_rec - w.t;
            xrec->push_back(w.x + w.V * h + 0.5 * a * h * h);
            next_rec += xrec_dt;
        }
        w.x += w.V * dt + 0.5 * a * dt * dt;
        S.sumV2dt += w.V * w.V * dt;
        if (!clampV) w.V += a * dt;
        w.t += dt;
        if (w.t >= tmax) break;
        const double v = gv(rng);
        const double rel = std::fabs(v - w.V);
        if (rel > C) continue;                     // guarded; ~never fires (C = 8 sigma)
        if (u01(rng) < rel / C) {
            const double Vnew = ((Mh - 1.0) * w.V + 2.0 * v) / (Mh + 1.0);
            if (clampV) { const double dp = Mh * (Vnew - w.V); S.imp2 += dp * dp; }
            else        { w.V = Vnew; }
            ++S.ncoll;
        }
    }
    return S;
}
} // namespace

int main() {
    std::printf("================================================================\n");
    std::printf(" TD08 - Fluctuation-Dissipation and Brownian Motion\n");
    std::printf(" J. C. Harvey, Melbourne - 2026-07-03\n");
    std::printf(" 1D Rayleigh gas, M/m = %.0f. One collision stream supplies BOTH\n", Mh);
    std::printf(" kicks and drag; no noise-amplitude parameter exists in this tool.\n");
    std::printf("================================================================\n\n");

    bool p0 = true, p2 = true, p3 = true;
    double gamma_T1 = 0;

    for (double T : {1.0, 4.0}) {
        std::printf("--- bath temperature T = %.1f ---\n", T);

        // ---- P0 + P1: free runs; x recorded every 100 time units ----
        const int    Kf = 400;
        const double Tfree = 100000.0, rec_dt = 100.0;
        const int    nrec = int(Tfree / rec_dt);
        double v2 = 0, ttot = 0; long ncoll = 0;
        // MSD over disjoint increments at lags (in units of rec_dt):
        const int lags[3] = {5, 10, 20};           // 500, 1000, 2000 time units
        double msd[3] = {0, 0, 0}; long cnt[3] = {0, 0, 0};
        for (int k = 0; k < Kf; ++k) {
            Walker w;
            std::vector<double> xr; xr.reserve(nrec + 2);
            RunStats s = evolve(w, Tfree, T, 0.0, false, &xr, rec_dt);
            v2 += s.sumV2dt; ttot += Tfree; ncoll += s.ncoll;
            for (int li = 0; li < 3; ++li) {
                const int L = lags[li];
                for (size_t i = 100; i + L < xr.size(); i += L) {   // skip 1e4 transient
                    const double d = xr[i + L] - xr[i];
                    msd[li] += d * d; ++cnt[li];
                }
            }
        }
        const double MV2 = Mh * v2 / ttot;
        std::printf("  P0: <M V^2>/k_BT = %.4f  (1 +- 2%%)  [%s]   (collision rate %.3f)\n",
                    MV2 / T, std::fabs(MV2 / T - 1.0) < 0.02 ? "PASS" : "FAIL",
                    double(ncoll) / (Kf * Tfree));
        if (std::fabs(MV2 / T - 1.0) > 0.02) p0 = false;

        // fit MSD(lag) = 2D*(lag - tau): slope over the 3 lag points
        double X[3], Y[3];
        for (int li = 0; li < 3; ++li) { X[li] = lags[li] * rec_dt; Y[li] = msd[li] / cnt[li]; }
        const double sx = X[0] + X[1] + X[2], sy = Y[0] + Y[1] + Y[2];
        const double sxx = X[0]*X[0] + X[1]*X[1] + X[2]*X[2];
        const double sxy = X[0]*Y[0] + X[1]*Y[1] + X[2]*Y[2];
        const double slope = (3 * sxy - sx * sy) / (3 * sxx - sx * sx);
        const double icpt = (sy - slope * sx) / 3.0;
        const double D = slope / 2.0, tau_fit = -icpt / slope;
        std::printf("  P1: MSD fit -> D = %.4f, velocity relaxation tau = %.1f\n", D, tau_fit);
        std::printf("      (tau is the TOY bath's collision timescale; the prompt's ~t_P claim\n");
        std::printf("       is untestable here and is classed OPEN, not asserted.)\n");

        // ---- P2: mobility from the SAME machinery under constant force ----
        const double gamma_est = T / D;
        const double F1 = 0.05 * std::sqrt(T) * gamma_est;   // V_drift target 0.05 sqrt(T)
        auto drift_run = [&](double F) {
            const int Kd = 100; const double Td = 50000.0, Ttr = 2000.0;
            double sum = 0;
            for (int k = 0; k < Kd; ++k) {
                Walker w;
                evolve(w, Ttr, T, F, false);                 // transient
                const double x0 = w.x, t0 = w.t;
                evolve(w, Ttr + Td, T, F, false);
                sum += (w.x - x0) / (w.t - t0);
            }
            return sum / Kd;
        };
        const double Vd1 = drift_run(F1), Vd2 = drift_run(0.5 * F1);
        const double mu = Vd1 / F1, lin = Vd2 / Vd1;
        const double ratio = D / (mu * T);
        std::printf("  P2: F = %.5f -> V_drift = %.5f, mu = %.4f; linearity Vd(F/2)/Vd(F) = %.3f [%s]\n",
                    F1, Vd1, mu, lin, std::fabs(lin - 0.5) < 0.05 ? "ok" : "FAIL");
        std::printf("      D/(mu k_B T) = %.4f  (1 +- 2%%)  [%s]\n\n",
                    ratio, std::fabs(ratio - 1.0) < 0.02 ? "PASS" : "FAIL");
        if (std::fabs(ratio - 1.0) > 0.02 || std::fabs(lin - 0.5) > 0.05) p2 = false;
        if (T == 1.0) gamma_T1 = F1 / Vd1;
    }

    // ---- P3: zero-frequency FDT (T = 1, V clamped at 0) ----
    std::printf("P3: force-noise spectrum at zero frequency (T = 1, V clamped)\n");
    {
        const double T = 1.0;
        double imp2 = 0, ttot = 0;
        for (int k = 0; k < 64; ++k) {
            Walker w;
            RunStats s = evolve(w, 50000.0, T, 0.0, true);
            imp2 += s.imp2; ttot += 50000.0;
        }
        const double SF0 = imp2 / ttot;
        const double pred = 2.0 * gamma_T1 * T;
        std::printf("  S_F(0) = %.4f;  2 gamma k_B T = %.4f  (gamma = F/V_drift from P2)\n", SF0, pred);
        std::printf("  ratio = %.4f  (1 +- 3%%; O(m/M) = 1%% budget declared)  [%s]\n",
                    SF0 / pred, std::fabs(SF0 / pred - 1.0) < 0.03 ? "PASS" : "FAIL");
        if (std::fabs(SF0 / pred - 1.0) > 0.03) p3 = false;
        std::printf("  (white at low frequency - uncorrelated impulses on a held vortex;\n");
        std::printf("   roll-off sits at the collision rate, the toy's 'relay tick'.)\n\n");
    }

    std::printf("P4: Stokes-Einstein closure vs FD02 - DEFERRED as declared in RUN_LOG\n");
    std::printf("  (1D shot-noise toy has no 6 pi eta R; FD02's eta carries a documented x1.44;\n");
    std::printf("   producing a closure number here would be fabrication. OPEN.)\n\n");

    const bool all = p0 && p2 && p3;
    std::printf("================================================================\n");
    std::printf(" TD08 GATES: P0 %s | P1 D extracted | P2 %s | P3 %s | P4 DEFERRED\n",
                p0 ? "PASS" : "FAIL", p2 ? "PASS" : "FAIL", p3 ? "PASS" : "FAIL");
    std::printf(" No noise normalisation exists in this tool; the Einstein ratio and the\n");
    std::printf(" FDT ratio are OUTPUTS of one collision stream. (k_B bridge: %.4e J/K)\n", kB_SI);
    std::printf(" VERDICT: %s - see TD08_VERDICT.md\n", all ? "PASS" : "FAIL");
    std::printf("================================================================\n");
    return all ? 0 : 1;
}
