#!/usr/bin/env python3
# ================================================================
# closure_kink_isotone.py -- closure-kink isotone invariant test
# Phase 2026-07-30. Author: J. C. Harvey, Melbourne. Gateways binding.
#
# PRE-REGISTRATION (committed before the sweep; the only values known in
# advance are Ca-48 kink -29.0, Cr-52 kink -28.4, Cr-53 staggering -15.8,
# all disclosed -- they motivated the question and serve as instrument
# validation, not as findings of this run):
#
# Q1 -- CLOSURE INVARIANT. Claim under test: the 3-point compaction kink
#   at a magic-N closure is a property of the CLOSURE EVENT, constant
#   along the isotone, independent of triton occupancy n_t = N - Z.
#   Rival shape: occupancy-proportional |kink| ~ c * n_t (if tritons did
#   the compacting, Ca-48 at 8t should kink ~2x Cr-52 at 4t).
#   Adjudication, per isotone with >= 2 computable members: least-squares
#   constant model vs proportional-through-origin model; constant supported
#   if its RMS residual is smaller. Overall claim supported if the constant
#   model wins every isotone with >= 3 members AND no isotone shows |kink|
#   rising with n_t by a factor >= 1.5 across its span. Whole-range single
#   pass over every magic N in {8, 20, 28, 50, 82, 126} and every Z.
#
# Q2 -- LONE ROD INWARD (secondary). Seat law says the lone odd rod takes
#   the inward seat: an odd-N member should sit BELOW the midpoint of its
#   even-N neighbours. Census over ALL computable odd-N triples, all
#   chains. Supported if >= 70% sit below midpoint (sign census, whole
#   range, one pass). Scope note: the pairing account predicts the same
#   sign -- this tests our seat law's direction; shared form, so it
#   CANNOT DISCRIMINATE between accounts. Origin differs; stated.
#
# BACKGROUND FIELD: distribution of even-N kinks at non-magic N, for the
#   separation between closure kinks and the ordinary field.
#
# INSTRUMENT: kink(Z,N) = ( R(Z,N) - (R(Z,N-2)+R(Z,N+2))/2 ) * 1000
#   [milli-fm], identical to enrich_boundary_radius.py. VALIDATION GATE:
#   must reproduce Ca-48 -29.0 and Cr-52 -28.4 within 0.1 milli-fm or the
#   run aborts.
#
# Data: ATOMICUS/tools/_iaea_ground_states.csv (measured radii only).
# Output: ATOMICUS/reports/CLOSURE_KINK_ISOTONE_REPORT.md (regenerated --
# edit this tool, not the report).
# ================================================================
import csv, os

HERE = os.path.dirname(os.path.abspath(__file__))
ROOT = os.path.dirname(HERE)
CSV  = os.path.join(HERE, "_iaea_ground_states.csv")
OUT  = os.path.join(ROOT, "reports", "CLOSURE_KINK_ISOTONE_REPORT.md")
MAGIC = [8, 20, 28, 50, 82, 126]

def load():
    R = {}
    for r in csv.DictReader(open(CSV, encoding="utf-8")):
        try:
            z = int(r["z"]); n = int(r["n"]); rad = r["radius"].strip()
            if rad:
                R[(z, n)] = float(rad)
        except Exception:
            pass
    return R

def kink(R, z, n):
    a, b, c = R.get((z, n - 2)), R.get((z, n)), R.get((z, n + 2))
    return (b - (a + c) / 2) * 1000 if (a and b and c) else None

def main():
    R = load()

    # -- instrument validation on known answers (abort on failure) --
    v1, v2 = kink(R, 20, 28), kink(R, 24, 28)
    assert v1 is not None and abs(v1 - (-29.0)) < 0.1, f"validation failed Ca-48: {v1}"
    assert v2 is not None and abs(v2 - (-28.4)) < 0.1, f"validation failed Cr-52: {v2}"

    L = ["# Closure-Kink Isotone Report -- regenerated by tools/closure_kink_isotone.py",
         "",
         "Phase 2026-07-30. Instrument validated on known answers "
         f"(Ca-48 {v1:.1f}, Cr-52 {v2:.1f} milli-fm). Single pass, whole range.",
         ""]

    # ---- Q1: closure kinks along every magic-N isotone ----
    L += ["## Q1 -- closure kink along each magic-N isotone", ""]
    overall_ok, any3 = True, False
    for Nm in MAGIC:
        rows = []
        for z in range(2, 101):
            k = kink(R, z, Nm)
            if k is not None and Nm - z >= 0:      # inside the standard grammar
                rows.append((z, Nm - z, k))
        if not rows:
            L.append(f"- N={Nm}: no computable members (neighbour radii unmeasured)")
            continue
        mean = sum(k for _, _, k in rows) / len(rows)
        detail = " | ".join(f"Z={z} (n_t={nt}) {k:+.1f}" for z, nt, k in rows)
        L.append(f"- N={Nm} ({len(rows)} member(s)): {detail}")
        if len(rows) < 2:
            L.append("    single member -- no adjudication (pre-registration requires >= 2)")
            continue
        rms_c = (sum((k - mean) ** 2 for _, _, k in rows) / len(rows)) ** 0.5
        num = sum(k * nt for _, nt, k in rows); den = sum(nt * nt for _, nt, _ in rows)
        c = num / den if den else 0.0
        rms_p = (sum((k - c * nt) ** 2 for _, nt, k in rows) / len(rows)) ** 0.5
        verdict = "constant" if rms_c < rms_p else "proportional"
        span_ratio = None
        ks = sorted(rows, key=lambda r: r[1])
        if len(ks) >= 2 and ks[0][2] != 0:
            span_ratio = abs(ks[-1][2]) / abs(ks[0][2]) if ks[0][2] else None
        if len(rows) >= 3:
            any3 = True
            if verdict != "constant":
                overall_ok = False
        if span_ratio is not None and span_ratio >= 1.5 and ks[-1][1] > ks[0][1]:
            overall_ok = False
        L.append(f"    mean {mean:+.1f}, RMS const {rms_c:.1f} vs proportional {rms_p:.1f} "
                 f"-> **{verdict}**" + (f"; |kink| span ratio {span_ratio:.2f}" if span_ratio else ""))
    L += ["",
          f"**Q1 outcome:** {'SUPPORTED' if overall_ok else 'NOT supported'} "
          f"under the pre-registered criterion"
          + ("" if any3 else " -- CAVEAT: no isotone reached 3 computable members; "
             "the >= 3-member clause never engaged, so this is the weak form "
             "(2-member isotones and span-ratio guard only)"),
          ""]

    # ---- background field ----
    bg = [kink(R, z, n) for z in range(2, 101) for n in range(2, 160, 2)
          if n not in MAGIC and kink(R, z, n) is not None]
    if bg:
        bmean = sum(bg) / len(bg)
        bstd = (sum((k - bmean) ** 2 for k in bg) / len(bg)) ** 0.5
        L += ["## Background field (even N, non-magic)", "",
              f"- {len(bg)} computable kinks: mean {bmean:+.2f}, std {bstd:.2f} milli-fm",
              ""]

    # ---- Q2: lone-rod-inward staggering census ----
    below = total = 0
    for z in range(2, 101):
        for n in range(3, 159, 2):                  # odd N
            a, b, c = R.get((z, n - 1)), R.get((z, n)), R.get((z, n + 1))
            if a and b and c:
                total += 1
                if b < (a + c) / 2:
                    below += 1
    L += ["## Q2 -- lone rod inward (odd-N staggering census)", ""]
    if total:
        frac = below / total
        L += [f"- {below}/{total} odd-N members sit below the even-even midpoint "
              f"({100 * frac:.1f}%; pre-registered support threshold 70%)",
              f"- **Q2 outcome:** {'SUPPORTED' if frac >= 0.70 else 'NOT supported'}. "
              "Scope: the pairing account predicts the same sign -- shared form, "
              "cannot discriminate between accounts; the seat-law content is the "
              "direction (inward), which the census tests.",
              ""]

    # ---- post-hoc observations (NOT pre-registered; recorded for follow-up) ----
    closure_ks = []
    for Nm in MAGIC:
        for z in range(2, 101):
            k = kink(R, z, Nm)
            if k is not None and Nm - z >= 0:
                closure_ks.append((Nm, k))
    if closure_ks:
        negs = sum(1 for _, k in closure_ks if k < 0)
        by_N = {}
        for Nm, k in closure_ks:
            by_N.setdefault(Nm, []).append(k)
        trend = " | ".join(f"N={Nm}: {sum(v)/len(v):+.1f} (x{len(v)})"
                           for Nm, v in sorted(by_N.items()))
        L += ["## Post-hoc observations (not pre-registered)", "",
              f"- Sign: {negs}/{len(closure_ks)} computable closure kinks are negative "
              "(compaction), against a background field centred near zero.",
              f"- Closure-strength trend across tiers: {trend} milli-fm. The grip PEAKS "
              "at N=28 -- the first triton belt -- and fades with tier size; the "
              "pre-belt N=20 closure (single member) is weak. Follow-up question, "
              "not a claim: is closure grip a belt property?",
              ""]

    os.makedirs(os.path.dirname(OUT), exist_ok=True)
    open(OUT, "w", encoding="utf-8").write("\n".join(L) + "\n")
    print("\n".join(L))
    print(f"\nwritten: {OUT}")

if __name__ == "__main__":
    main()
